version: 2
updates:
  - package-ecosystem: npm
    directory: /
    assignees:
      - Rakambda
    schedule:
      interval: cron
      cronjob: 0 7 * * *
      timezone: Europe/Paris
    pull-request-branch-name:
      separator: '-'
    groups:
      eslint:
        patterns:
          - eslint
          - '@eslint/*'
          - '@stylistic/eslint-plugin-ts'
          - '@typescript-eslint/*'
      octokit:
        patterns:
          - '@octokit/*'
